apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ui-pipeline
spec:
  params:
    - name: GIT_REPOSITORY
      default: https://github.com/leandroberetta/right-lyrics
    - name: GIT_REVISION
      default: master
  workspaces:
    - name: source
  tasks:
    - name: clone
      taskRef:
        name: git
      workspaces:
        - name: source
          workspace: source
      params:
        - name: REPOSITORY
          value: $(params.GIT_REPOSITORY)
        - name: REVISION
          value: $(params.GIT_REVISION)
    - name: install
      taskRef:
        name: npm
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: source
      params:
        - name: COMMAND
          value: install
        - name: CONTEXT_PATH
          value: lyrics-ui
    - name: generate
      taskRef:
        name: npm
      runAfter:
        - install
      workspaces:
        - name: source
          workspace: source
      params:
        - name: COMMAND
          value: run build
        - name: CONTEXT_PATH
          value: lyrics-ui  
    - name: build
      taskRef:
        name: s2i
      runAfter:
        - generate
      workspaces:
        - name: source
          workspace: source
      params:
        - name: IMAGE
          value: example.org/right-lyrics/lyrics-ui:latest
        - name: BASE_IMAGE
          value: registry.access.redhat.com/rhscl/nginx-114-rhel7
        - name: CONTEXT_PATH
          value: lyrics-ui/build
        - name: TLS_VERIFY
          value: "false"
        - name: FORMAT
          value: docker
    - name: deploy
      taskRef:
        name: kubectl
      runAfter:
        - build
      workspaces:
        - name: source
          workspace: source
      params:
        - name: COMMAND
          value: apply -k $(workspaces.source.path)/lyrics-ui/k8s/overlays/dev